### PR TITLE
wejeje

### PR DESCRIPTION
**Pull request by Miguel-Escobar**
Arreglé su código.

### CODE REVIEW

**Comment by SirCrocker** [comment]
Main program is not enclosed inside a function, please fix!

**Review by SirCrocker — CHANGES_REQUESTED** [review]
Please enclose the main functionality inside a function

**Comment by Miguel-Escobar** [comment]
# cowardice

**Comment by SirCrocker** [comment]
> # cowardice

This a temple of code. The pull request has been closed to an ad hominem attack. Good day to you.

**Pull request closed without merging**
